# PIPELINE DEFINITION
# Name: train-test-split
# Inputs:
#    dataframe: system.Dataset
# Outputs:
#    X_test: system.Dataset
#    X_train: system.Dataset
#    y_test: system.Dataset
#    y_train: system.Dataset
components:
  comp-train-test-split:
    executorLabel: exec-train-test-split
    inputDefinitions:
      artifacts:
        dataframe:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        X_test:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        X_train:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        y_test:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        y_train:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-train-test-split:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_test_split
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.11.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef train_test_split(\n    dataframe: dsl.Input[dsl.Dataset],\n \
          \   X_train: dsl.Output[dsl.Dataset],\n    X_test : dsl.Output[dsl.Dataset],\n\
          \    y_train: dsl.Output[dsl.Dataset],\n    y_test: dsl.Output[dsl.Dataset]\n\
          \    ):\n  import pandas as pd\n  import numpy as np\n  from sklearn.model_selection\
          \ import train_test_split\n  import os\n\n  df = pd.read_csv(dataframe.path)\n\
          \n\n  target_column = 'class'\n\n  X = df.loc[:, df.columns != target_column]\n\
          \  y = df.loc[:, df.columns == target_column]\n\n  X_train, X_test, y_train,\
          \ y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=47)\n\
          \n  np.save(X_train.path, X_train)\n  np.save(X_test.path, X_test)\n  np.save(y_train.path,\
          \ y_train)\n  np.save(y_test.path, y_test)\n\n"
        image: python:3.12
pipelineInfo:
  name: train-test-split
root:
  dag:
    outputs:
      artifacts:
        X_test:
          artifactSelectors:
          - outputArtifactKey: X_test
            producerSubtask: train-test-split
        X_train:
          artifactSelectors:
          - outputArtifactKey: X_train
            producerSubtask: train-test-split
        y_test:
          artifactSelectors:
          - outputArtifactKey: y_test
            producerSubtask: train-test-split
        y_train:
          artifactSelectors:
          - outputArtifactKey: y_train
            producerSubtask: train-test-split
    tasks:
      train-test-split:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-test-split
        inputs:
          artifacts:
            dataframe:
              componentInputArtifact: dataframe
        taskInfo:
          name: train-test-split
  inputDefinitions:
    artifacts:
      dataframe:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
  outputDefinitions:
    artifacts:
      X_test:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
      X_train:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
      y_test:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
      y_train:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
schemaVersion: 2.1.0
sdkVersion: kfp-2.11.0
